menu:
  首页: /
  归档: /archives

widgets: 
- search
- category
- tag
#- twitter

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: true
  pinterest: false

fancybox: true

google_analytics:
rss: